# Generated by Django 6.0.2 on 2026-02-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_alter_subject_subjectcatagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherSerial', models.IntegerField()),
                ('teacherId', models.IntegerField()),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherCardNo', models.IntegerField(unique=True)),
                ('teacherDesignation', models.CharField(max_length=100)),
                ('teacherInfo', models.TextField()),
                ('teacherCategory', models.CharField(choices=[('teacher', 'Teacher'), ('assistant', 'Assistant')], max_length=20)),
                ('teacherEmail', models.CharField(unique=True)),
                ('teacherCreated', models.DateTimeField(auto_now_add=True)),
                ('teacherSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
