# Generated by Django 6.0.2 on 2026-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectId', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50, unique=True)),
                ('subjectCatagory', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('alevel', 'A Level'), ('olevel', 'O Level')], max_length=50)),
                ('subjectCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
