# Generated by Django 6.0.2 on 2026-02-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCatagory',
            field=models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('alevel', 'A Level'), ('olevel', 'O Level'), ('general', 'General')], max_length=50),
        ),
    ]
